let example1 = true;
let example2 = false;
let example3 = 65;
let example4 = 'hello';
let example5 = '';
let example6 = undefined;
let example7 = NaN;
let example8 = -5;
let example9 = 0;
let example10 = null;

console.log(Boolean(example1));
console.log(Boolean(example2));
console.log(Boolean(example3));
console.log(Boolean(example4));
console.log(Boolean(example5));
console.log(Boolean(example6));
console.log(Boolean(example7));
console.log(Boolean(example8));
console.log(Boolean(example9));
console.log(Boolean(example10));